# Generated by Django 2.1.5 on 2019-11-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastname',
            name='main_model',
        ),
        migrations.DeleteModel(
            name='LastName',
        ),
    ]
