# Generated by Django 2.1.5 on 2019-11-21 15:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_lastname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastName',
            new_name='Pofile',
        ),
    ]
