# Generated by Django 2.1.5 on 2019-11-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_children'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='children',
            options={'verbose_name': 'Ребенок', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterField(
            model_name='children',
            name='bored',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
