# Generated by Django 2.1.5 on 2019-11-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191122_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='img',
            field=models.ImageField(default='default.png', upload_to='users_avatar', verbose_name='Изображение ребенка'),
        ),
    ]
